version: '3.8'

services:
  blue_app:
    image: ${BLUE_IMAGE}
    container_name: blue_app
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue
    ports:
      - "8081:${PORT}"
    restart: unless-stopped

  green_app:
    image: ${GREEN_IMAGE}
    container_name: green_app
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green
    ports:
      - "8082:${PORT}"
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    depends_on:
      - blue_app
      - green_app
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - PORT=${PORT}
    command: >
      /bin/sh -c "envsubst '$$ACTIVE_POOL $$PORT' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf &&
                  nginx -g 'daemon off;'"
    restart: unless-stopped
