services:
  blue_app:
    image: "${BLUE_IMAGE}"
    container_name: blue_app
    ports:
      - "8081:3000"
    environment:
      RELEASE_ID: "${RELEASE_ID_BLUE}"
      APP_POOL: blue
      PORT: "${PORT}"
      HOST: 0.0.0.0

  green_app:
    image: "${GREEN_IMAGE}"
    container_name: green_app
    ports:
      - "8082:3000"
    environment:
      RELEASE_ID: "${RELEASE_ID_GREEN}"
      APP_POOL: green
      PORT: "${PORT}"
      HOST: 0.0.0.0
